import type { Agent, Job, Log, GitStatus, Port, Service, Action } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'agent-001',
    name: 'Main Orchestrator',
    status: 'busy',
    currentModel: 'claude-sonnet-4',
    lastTaskSummary: 'Processing GitHub issue #234 - API endpoint optimization',
    uptime: '3d 12h 45m',
    tasksCompleted: 1247,
  },
  {
    id: 'agent-002',
    name: 'Code Reviewer',
    status: 'idle',
    currentModel: 'gpt-4o',
    lastTaskSummary: 'Completed PR review for feature/auth-refactor',
    uptime: '5d 2h 18m',
    tasksCompleted: 892,
  },
  {
    id: 'agent-003',
    name: 'Debugger',
    status: 'running',
    currentModel: 'claude-sonnet-4',
    lastTaskSummary: 'Investigating memory leak in worker thread',
    uptime: '1d 8h 33m',
    tasksCompleted: 456,
  },
  {
    id: 'agent-004',
    name: 'Documentation',
    status: 'idle',
    currentModel: 'gpt-4o-mini',
    lastTaskSummary: 'Generated API docs for v2.3.0',
    uptime: '2d 14h 12m',
    tasksCompleted: 234,
  },
  {
    id: 'agent-005',
    name: 'Security Scanner',
    status: 'failed',
    currentModel: 'claude-sonnet-4',
    lastTaskSummary: 'Dependency vulnerability scan failed - timeout',
    uptime: '0d 0h 45m',
    tasksCompleted: 567,
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-001',
    status: 'running',
    startTime: new Date(Date.now() - 1000 * 60 * 15),
    agentChain: ['agent-001', 'agent-003'],
    description: 'Refactor authentication middleware',
    progress: 67,
  },
  {
    id: 'job-002',
    status: 'success',
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 2),
    endTime: new Date(Date.now() - 1000 * 60 * 45),
    agentChain: ['agent-002'],
    description: 'Review pull request #445',
    progress: 100,
  },
  {
    id: 'job-003',
    status: 'queued',
    startTime: new Date(Date.now() + 1000 * 60 * 5),
    agentChain: ['agent-004'],
    description: 'Update README with new installation steps',
    progress: 0,
  },
  {
    id: 'job-004',
    status: 'failed',
    startTime: new Date(Date.now() - 1000 * 60 * 30),
    endTime: new Date(Date.now() - 1000 * 60 * 28),
    agentChain: ['agent-005'],
    description: 'Run security audit on dependencies',
    progress: 23,
  },
  {
    id: 'job-005',
    status: 'running',
    startTime: new Date(Date.now() - 1000 * 60 * 45),
    agentChain: ['agent-001', 'agent-002'],
    description: 'Implement rate limiting for API endpoints',
    progress: 34,
  },
  {
    id: 'job-006',
    status: 'success',
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 4),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 3),
    agentChain: ['agent-003'],
    description: 'Fix database connection pooling issue',
    progress: 100,
  },
];

export const mockLogs: Log[] = [
  {
    id: 'log-001',
    message: 'Agent agent-001 started task: Refactor authentication middleware',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    type: 'info',
    source: 'orchestrator',
  },
  {
    id: 'log-002',
    message: 'GitHub API rate limit approaching: 45 requests remaining',
    timestamp: new Date(Date.now() - 1000 * 60 * 12),
    type: 'debug',
    source: 'github',
  },
  {
    id: 'log-003',
    message: 'Security scan failed: Connection timeout to npm registry',
    timestamp: new Date(Date.now() - 1000 * 60 * 28),
    type: 'error',
    source: 'security',
  },
  {
    id: 'log-004',
    message: 'Job job-002 completed successfully in 1h 15m',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    type: 'info',
    source: 'orchestrator',
  },
  {
    id: 'log-005',
    message: 'Memory usage for agent-003: 512MB / 2GB',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    type: 'debug',
    source: 'monitor',
  },
  {
    id: 'log-006',
    message: 'Port 8000 conflict detected: Process node (PID 12345) already listening',
    timestamp: new Date(Date.now() - 1000 * 60 * 8),
    type: 'error',
    source: 'network',
  },
  {
    id: 'log-007',
    message: 'Agent agent-004 idle for 30 minutes',
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
    type: 'debug',
    source: 'monitor',
  },
  {
    id: 'log-008',
    message: 'New job queued: Update README with new installation steps',
    timestamp: new Date(Date.now() - 1000 * 60),
    type: 'info',
    source: 'orchestrator',
  },
];

export const mockGitStatus: GitStatus = {
  repoName: 'openclaw-core',
  branch: 'feature/mission-control-ui',
  recentCommits: [
    {
      hash: 'a1b2c3d',
      message: 'feat: add glassmorphism styling to dashboard',
      author: 'Sai',
      timestamp: new Date(Date.now() - 1000 * 60 * 30),
    },
    {
      hash: 'e4f5g6h',
      message: 'fix: resolve port conflict detection logic',
      author: 'Agent-003',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    },
    {
      hash: 'i7j8k9l',
      message: 'refactor: improve agent task scheduling',
      author: 'Agent-001',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
    },
    {
      hash: 'm0n1o2p',
      message: 'docs: update API documentation',
      author: 'Agent-004',
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
    },
  ],
  isDirty: true,
  ahead: 3,
  behind: 0,
};

export const mockPorts: Port[] = [
  { portNumber: 3000, inUseBy: 'mission-control', conflictStatus: 'in-use', service: 'React Dev Server' },
  { portNumber: 8000, inUseBy: 'simple-rest-api', conflictStatus: 'in-use', service: 'Node.js API' },
  { portNumber: 8080, inUseBy: null, conflictStatus: 'free' },
  { portNumber: 5432, inUseBy: 'postgres', conflictStatus: 'in-use', service: 'PostgreSQL' },
  { portNumber: 6379, inUseBy: 'redis', conflictStatus: 'in-use', service: 'Redis' },
  { portNumber: 9000, inUseBy: 'grafana', conflictStatus: 'in-use', service: 'Grafana' },
];

export const mockServices: Service[] = [
  {
    id: 'svc-001',
    name: 'OpenClaw Gateway',
    status: 'running',
    uptime: '5d 12h 30m',
    memory: '128MB',
    cpu: '2.3%',
    port: 8080,
  },
  {
    id: 'svc-002',
    name: 'Agent Orchestrator',
    status: 'running',
    uptime: '3d 8h 45m',
    memory: '256MB',
    cpu: '5.7%',
    port: 8081,
  },
  {
    id: 'svc-003',
    name: 'Log Aggregator',
    status: 'running',
    uptime: '5d 12h 28m',
    memory: '64MB',
    cpu: '1.2%',
    port: 8082,
  },
  {
    id: 'svc-004',
    name: 'Git Sync Service',
    status: 'error',
    uptime: '0d 0h 15m',
    memory: '32MB',
    cpu: '0%',
    port: 8083,
  },
  {
    id: 'svc-005',
    name: 'Metrics Collector',
    status: 'running',
    uptime: '2d 4h 12m',
    memory: '96MB',
    cpu: '3.1%',
    port: 8084,
  },
];

export const mockActions: Action[] = [
  {
    id: 'action-001',
    name: 'Restart All Agents',
    description: 'Gracefully restart all agent processes',
    category: 'System',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 24),
    runCount: 12,
  },
  {
    id: 'action-002',
    name: 'Clear Job Queue',
    description: 'Remove all queued jobs from the pipeline',
    category: 'Jobs',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 48),
    runCount: 3,
  },
  {
    id: 'action-003',
    name: 'Export Logs',
    description: 'Download system logs as JSON archive',
    category: 'System',
    runCount: 45,
  },
  {
    id: 'action-004',
    name: 'Sync Git Repositories',
    description: 'Pull latest changes from all tracked repositories',
    category: 'Git',
    lastRun: new Date(Date.now() - 1000 * 60 * 30),
    runCount: 156,
  },
  {
    id: 'action-005',
    name: 'Run Security Audit',
    description: 'Scan all dependencies for vulnerabilities',
    category: 'Security',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 12),
    runCount: 8,
  },
  {
    id: 'action-006',
    name: 'Backup Configuration',
    description: 'Create backup of all service configurations',
    category: 'System',
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
    runCount: 4,
  },
];

export const systemMetrics = {
  totalAgents: mockAgents.length,
  activeJobs: mockJobs.filter(j => j.status === 'running').length,
  queuedJobs: mockJobs.filter(j => j.status === 'queued').length,
  completedJobsToday: 23,
  failedJobsToday: 2,
  avgJobDuration: '12m 34s',
  systemUptime: '5d 12h 30m',
  cpuUsage: 34,
  memoryUsage: 62,
  diskUsage: 45,
};